"""The small, read-only technical-stack adapter protocol."""

from pathlib import Path
from typing import Protocol

from .models import DetectionEvidence


class ProjectAdapter(Protocol):
    adapter_id: str
    display_name: str

    def detect(self, repo_root: Path) -> DetectionEvidence: ...
    def source_patterns(self) -> tuple[str, ...]: ...
    def test_patterns(self) -> tuple[str, ...]: ...
    def sensitive_path_patterns(self) -> tuple[str, ...]: ...
    def generated_path_patterns(self) -> tuple[str, ...]: ...
    def ignored_path_patterns(self) -> tuple[str, ...]: ...
    def default_test_command_ids(self) -> tuple[str, ...]: ...
    def default_quality_command_ids(self) -> tuple[str, ...]: ...
    def root_markers(self) -> tuple[str, ...]: ...
